// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SmartApartmentSystem.Infrastructure.Data;

namespace SmartApartmentSystem.Data.Migrations
{
    [DbContext(typeof(SasDbContext))]
    [Migration("20181230075110_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Data.Models.Module", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<byte>("ActualStatus");

                    b.Property<int>("DeviceId");

                    b.Property<byte>("ExpectedStatus");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDisabled");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            ActualStatus = (byte)0,
                            DeviceId = 1,
                            ExpectedStatus = (byte)0,
                            IsActive = false,
                            IsDisabled = false,
                            Name = "Boiler"
                        });
                });

            modelBuilder.Entity("Data.Models.Schedule", b =>
                {
                    b.Property<byte>("ModuleId");

                    b.Property<int>("Day");

                    b.Property<byte>("Hour");

                    b.Property<byte>("Minutes");

                    b.Property<byte>("Status");

                    b.HasKey("ModuleId", "Day", "Hour", "Minutes");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ModuleId = (byte)1,
                            Day = 2,
                            Hour = (byte)8,
                            Minutes = (byte)30,
                            Status = (byte)25
                        },
                        new
                        {
                            ModuleId = (byte)1,
                            Day = 2,
                            Hour = (byte)9,
                            Minutes = (byte)0,
                            Status = (byte)20
                        });
                });

            modelBuilder.Entity("Data.Models.Schedule", b =>
                {
                    b.HasOne("Data.Models.Module", "Module")
                        .WithMany("Schedules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
